name: Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23"

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test -v ./...

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          cd rust
          cargo build

      - name: Run Rust Tests
        run: |
          cd rust
          cargo test
